#-------------------------------
# General Site Settings

menu:
#- {name: 'Projects', url: ''}
#- {name: 'Blog', url: 'pages/blog.html'}
- {name: 'About', url: 'pages/about.html'}
#- {name: 'Contact', url: 'pages/contact.html'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Personal portfolio powered by Jekyll and GitHub Pages '
  rel-author: 'https://plus.google.com/u/0/#'
  rel-publisher: 'https://plus.google.com/u/0/#'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065


google-analytics-ua: true

# If you are not using Google Analytics, please change 'google-ID' to an empty string

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'thathungrymind'

#-------------------------------
# About Section

about: >
  ## Hi! I'm Jack
  
  <img src="360noscopeheadshot.jpg" alt="noscopeheadshot" width="500"/>
  
  
  I'm a mechanical engineer at UC Berkeley, an engine team member on Berkeley Formula Racing, 
  and an assembly technician at covariant.ai. I'm currently looking for internships in 2020.
  
  Interests include:
  
  - mechanical design<BR>
  
  - manufacturing<BR>
  
  - automotive engineering<BR>
  
  - computer science<BR>
  
  - rock climbing<BR>
  
  - jazz<BR>
  
  - Cleon Peterson<BR>
  

  Please feel free to reach out to me through my email!
  
  #### jackbwallis@berkeley.edu
  
contact: >
  # Contact

  You may contact me [through my email](mailto:l.nguyen.paul@gmail.com) or [tweet at me](https://twitter.com/intent/tweet?text=%40paululele) if you have any questions or would like to bring up any issues.

#-------------------------------
# Work Section

projects:
- {name: 'FSAE Cooling System', folder: 'proj-1', file: 'projects/proj-1.html'}
- {name: 'IoL', folder: 'proj-6', file: 'projects/proj-6.html'}
- {name: 'Wind Turbine', folder: 'proj-2', file: 'projects/proj-2.html'}
- {name: 'Crossplane V8', folder: 'proj-3', file: 'projects/proj-3.html'}
- {name: 'Sound Machine', folder: 'proj-8', file: 'projects/proj-8.html'}
- {name: 'Stomper', folder: 'proj-4', file: 'projects/proj-4.html'}
- {name: 'KUGU Home', folder: 'proj-5', file: 'projects/proj-5.html'}
#- {name: 'KTM 350', folder: 'proj-8', file: 'projects/proj-8.html'}

#-------------------------------
# Contact Section

social:
#- {icon: 'twitter', link: '#'}
#- {icon: 'instagram', link: '#'}
#- {icon: 'github', link: '#'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/jackbwallis/'}
- {icon: 'envelope', link: 'mailto:jackbwallis@berkeley.edu'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
