#-------------------------------
# General Site Settings

menu:
#- {name: 'Projects', url: ''}
- {name: 'Map', url: 'pages/blog.html'}
- {name: 'About', url: 'pages/about.html'}
#- {name: 'Contact', url: 'pages/contact.html'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'A personal mechanical engineering and product design portfolio.'
  rel-author: 'https://plus.google.com/u/0/#'
  rel-publisher: 'https://plus.google.com/u/0/#'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065


google-analytics-ua: true

# If you are not using Google Analytics, please change 'google-ID' to an empty string

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'thathungrymind'

#-------------------------------
# About Section

about: >
  ## Hi! I'm Jack <BR>
  
  <img src="360noscope.jpg" alt="noscopeheadshot" width="600"/>
  
  # Here's my [resume](WallisJackResume.pdf)
    
  I'm a mechanical engineer at UC Berkeley, an engine team member on Berkeley Formula Racing, 
  and a hardware intern at covariant.ai. I'm currently looking for internships.
  
  Interests include:
  
  - mechanical design<BR>
  
  - manufacturing<BR>
  
  - automotive engineering<BR>
  
  - computer science<BR>
  
  - rock climbing<BR>
  
  - jazz<BR>
  
  - Cleon Peterson<BR>
  

  Please feel free to reach out to me through my email:
  
  #### jackbwallis@berkeley.edu
  
contact: >
  # Contact

  You may contact me [through my email](mailto:l.nguyen.paul@gmail.com) or [tweet at me](https://twitter.com/intent/tweet?text=%40paululele) if you have any questions or would like to bring up any issues.

#-------------------------------
# Work Section

projects:
- {name: 'FSAE Cooling System', folder: 'cooling', file: 'projects/cooling.html'}
- {name: 'covariant.ai', folder: 'covariant', file: 'projects/covariant.html'}
- {name: 'Sentry', folder: 'sentry', file: 'projects/sentry.html'}
- {name: 'IoL', folder: 'iol', file: 'projects/iol.html'}
- {name: 'Wind Turbine', folder: 'turbine', file: 'projects/turbine.html'}
- {name: 'Crossplane V8', folder: 'v8', file: 'projects/v8.html'}
- {name: 'Sound Machine', folder: 'sound', file: 'projects/sound.html'}
- {name: 'Stomper', folder: 'stomper', file: 'projects/stomper.html'}
- {name: 'KUGU Home', folder: 'kugu', file: 'projects/kugu.html'}
#- {name: 'KTM 350', folder: 'proj-8', file: 'projects/proj-8.html'}

#------------------------------
# Contact Section

social:
#- {icon: 'twitter', link: '#'}
#- {icon: 'instagram', link: '#'}
#- {icon: 'github', link: '#'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/jackbwallis/'}
- {icon: 'envelope', link: 'mailto:jackbwallis@berkeley.edu'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
